# ==================== Proyecto ====================
spring.application.name=innovatech-ms-gestion-recursos
server.port=8082

# ==================== JPA ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/innovatech_recursos_db
spring.datasource.username=postgres
spring.datasource.password=15.RERM#@Vs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================== JWT ====================
jwt.secret=innovatech2026_fullstack3_RichardMoreano
jwt.expiration=86400000   # 24 horas

# ==================== Otros ====================
spring.profiles.active=dev